# Generated by Django 3.2.9 on 2021-12-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='content',
        ),
    ]
