# Generated by Django 3.2.9 on 2021-12-09 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0002_remove_fileupload_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile2', models.ImageField(blank=True, null=True, upload_to='crop/')),
                ('fileupload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans.fileupload')),
            ],
        ),
    ]
